/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "/home/jonas/Dev/my-mme/tools/oai/openair-cn/SRC/S1AP/MESSAGES/ASN1/R10.5/S1AP-Containers.asn"
 * 	`asn1c -gen-PER -fcompound-names -S`
 */

#include "PrivateIE-Field.h"

