# Quarkus properties
quarkus.application.name=my-mme
quarkus.log.level=INFO

# MME Configuration
mme.s1ap.port=36412
mme.s1ap.host=0.0.0.0

# Redis Configuration
quarkus.redis.hosts=redis://localhost:6379

# Diameter S6a Configuration
mme.s6a.destination-host=ocs.demo.org
mme.s6a.destination-realm=server.test.com
mme.s6a.origin-host=ocsclient
mme.s6a.origin-realm=client.test.com
mme.s6a.visited-plmn-id=00F110

quarkus.diameter.local-peer.uri=aaa://testclient:1812
quarkus.diameter.local-peer.ip-addresses=0.0.0.0, 127.0.0.1
quarkus.diameter.local-peer.realm=client.test.com
quarkus.diameter.local-peer.product-name=Diameter Test Client
quarkus.diameter.local-peer.firmware-revision=1
quarkus.diameter.local-peer.applications.0.auth-appl-id=16777251
quarkus.diameter.local-peer.applications.0.vendor-id=10415

quarkus.diameter.network.peers.1.peer-uri=aaa://ocs.demo.org:3868
quarkus.diameter.network.peers.1.ip=127.0.0.1
quarkus.diameter.network.peers.1.attempt-connect=true
quarkus.diameter.network.peers.1.rating=0

quarkus.diameter.network.realms."server.test.com".peers=localhost
quarkus.diameter.network.realms."server.test.com".local-action=local
quarkus.diameter.network.realms."server.test.com".dynamic=false
quarkus.diameter.network.realms."server.test.com".exp-time=3
quarkus.diameter.network.realms."server.test.com".application-id.auth-appl-id=16777251

# GTP Configuration
mme.gtp.sgw-ip=127.0.0.1
mme.gtp.sgw-port=2123
mme.gtp.local-ip=127.0.0.1
mme.gtp.local-port=2123
